language: cpp

compiler:
  - clang

script:
  - make tests


notifications:
  slack:
    rooms: 
      - nyuoop:Pt31RgSKx7T34S8fyZ4NI7tj #your_TA_slack_channel
    on_success: always
    on_failure: never
  email:
    recipients:
      - your_email@nyu.edu
    on_success: always
    on_failure: always  
