language: cpp

compiler:
  - clang

script:
  - make tests

notifications:
  email:
    recipients:
      - ejc369@nyu.edu
    on_success: always
    on_failure: never

    recipients:
      - mz2325@nyu.edu
    on_success: always
    on_failure: always  
